force-app/main/default/objects/SF_Training_Topic__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <label>Instructor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manasi</fullName>
            </value>
            <value>
                <fullName>Vinod</fullName>
            </value>
            <value>
                <fullName>Kumar</fullName>
            </value>
            <value>
                <fullName>Rohan</fullName>
            </value>
            <value>
                <fullName>Sunanda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Topic_Category__c.field-meta.xml
<CustomField>
    <fullName>Topic_Category__c</fullName>
    <label>Topic Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SF_Training_Topic__c/fields/Topic_Name__c.field-meta.xml
<CustomField>
    <fullName>Topic_Name__c</fullName>
    <label>Topic Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SfApexClass.cls
public with sharing class SfApexClass {
    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getAllTopics(){
        return [select ID,	Topic_Name__c,Topic_Category__c,Instructor__c from SF_Training_Topic__c WITH SECURITY_ENFORCED];
    }

    @AuraEnabled(cacheable=true)
    public static List<SF_Training_Topic__c> getAllTopicsByCat(String strcat) {
        return [select ID,	Topic_Name__c,Topic_Category__c,Instructor__c from SF_Training_Topic__c where Topic_Category__c like : strcat WITH SECURITY_ENFORCED];
    }



}